Repository linuxboot/heads, pull requests merged in 2025-04, with the labels that each got.

#1947 bugfix: modules/coreboot + blobs/xx80: rely on github for git, not review.coreboot.org
  .circleci/config.yml
  blobs/xx80/download_clean_deguard_me_pad_tb.sh
  modules/coreboot
Labels: bug, CI

#1950 CircleCI: first layer cache: musl-cross-make+packages downloaded, was still pointing to old musl-cross-make
  .circleci/config.yml
Labels: enhancement, buildsystem

#1943 Add kconfig to use blobs on 24.12 boards coreboot configs and proper build output to console
  Makefile
  config/coreboot-novacustom-v540tu.config
  config/coreboot-novacustom-v560tu.config
  config/coreboot-optiplex-7019_9010-maximized.config
  config/coreboot-optiplex-7019_9010_TXT-maximized.config
  config/coreboot-t420-maximized.config
  config/coreboot-t420.config
  config/coreboot-t430-legacy-flash.config
  config/coreboot-t430-legacy.config
  config/coreboot-t430-maximized.config
  config/coreboot-t440p.config
  config/coreboot-t530-maximized.config
  config/coreboot-w530-maximized.config
  config/coreboot-w541.config
  config/coreboot-x220-maximized.config
  config/coreboot-x220.config
  config/coreboot-x230-legacy-flash.config
  config/coreboot-x230-legacy.config
  config/coreboot-x230-maximized-fhd_edp.config
  config/coreboot-x230-maximized.config
  config/coreboot-z220-cmt.config
Labels: bug

#1945 BUGFIXes : luks-functions + oem-factory-reset: fix logic for nvme/non-nvme based LUKS partitions checks + Force GPG Comment under oem-factory-reset + reset nk3 secrets app when in-memory keygen
  initrd/bin/kexec-select-boot
  initrd/bin/oem-factory-reset
  initrd/bin/tpmr
  initrd/etc/functions
  initrd/etc/luks-functions
Labels: bug, UX, automated testing

#1958 UX bugfix: kexec-save-default: suppress "Failed to set up async io, using sync io" warning thrown by lvm vgscan
  initrd/bin/kexec-save-default
  initrd/etc/luks-functions
Labels: bug, UX

#1959 patches/coreboot-24.12/0010-cbmem_tpm-clear_whole_log_on_creation.patch: readd missing uptream cbmem patch for TPM 1.2
  patches/coreboot-24.12/0010-cbmem_tpm-clear_whole_log_on_creation.patch
Labels: bug, wontfix, upstream

#1964 fix change passphrase
  initrd/etc/luks-functions
Labels: bug
